### ISSUE TITLE
 return self._apply(lambda t: t.cuda(device)) RuntimeError: Invalid device, must be cuda device

### ISSUE THREAD

**Issue by gitihobo** [seungheondoh/lp-music-caps#3]
My device is cuda compatible, what is going on? could it be the code? I only have 1 gpu btw

**Comment by gitihobo** [comment]
PyTorch 2.0+cpu

**Comment by gitihobo** [comment]
I installed correct torch version now, but I am getting ERROR:    Exception in ASGI application KeyError: 'dataset'

**Comment by gitihobo** [comment]
Anaconda environment python=3.10 

Windows 10 amd processor nvdia 16 gb

**Comment by gitihobo** [comment]
Installed huggingface demo git pull, requirements.txt and /demo python app.py

**Comment by seungheondoh** [comment]
How about try this process

```
git clone https://github.com/seungheondoh/lp-music-caps.git
cd lp-music-caps
pip install -e .
cd demo
python app.py
```

**Comment by gitihobo** [comment]
Same issue: 

Traceback (most recent call last):
  File "A:\\anaconda3\envs\lpcap\lp-music-caps\demo\app.py", line 26, in <module>
    model = model.cuda(device)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: Invalid device, must be cuda device

**Comment by gitihobo** [comment]
Same issue when opening local link

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\gradio\routes.py", line 291, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "A:\\anaconda3\envs\lpcap\lib\site-packages\gradio\blocks.py", line 528, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'

**Comment by seungheondoh** [comment]
I think this issue is related to gradio app.
How about try reinstall gradio?

```
pip uninstall gradio
pip install gradio
```

**Comment by gitihobo** [comment]
problem solved
